name: sefawilliamsmotors
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  get: ^4.6.6
  bottom_navy_bar: ^6.0.0
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  animations: ^2.0.11
  provider: ^6.1.2
  dropdown_button2: ^2.3.9
  flutter_cart: ^0.0.9
  get_storage: ^2.1.1
  flutter_login: ^5.0.0
  webview_flutter: ^4.7.0
  flutter_stripe: ^10.1.1
  razorpay_flutter: ^1.3.6
  onesignal_flutter: ^5.1.6
  pay_with_paystack: ^1.0.8

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.jpg"
  adaptive_icon_background : "#ffffff"
  adaptive_icon_foreground : "assets/images/logo.jpg"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
